name: add a file
on: 
  workflow_dispatch:
jobs:
  add-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config --global user.name Cyber-Alexei
          git config --global user.email 150178624+Cyber-Alexei@users.noreply.github.com
      - name: Commit the new file
        run: |
          echo "New file Alexei 123" > newfile.txt
          git add newfile.txt
          git commit -m "newfile added"
          git pull origin main --rebase
          git push origin main
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
      
    
